-- Fresh databases only; MySQL 8 with utf8mb4_0900_ai_ci collation.
create table accessibility_reports (follow_up_date date, follow_up_required bit, incident_date date, report_date date not null, resolved bit, resolved_date date, assigned_to bigint, created_at datetime(6) not null, id bigint not null auto_increment, reported_by bigint, school_id bigint not null, student_id bigint not null, updated_at datetime(6), severity varchar(50), location varchar(200), title varchar(200) not null, action_taken TEXT, description TEXT not null, related_disability enum ('AUTISM','COGNITIVE','HEARING','MENTAL_HEALTH','MULTIPLE','OTHER','PHYSICAL','SPEECH','VISUAL'), primary key (id)) engine=InnoDB;
create table classrooms (capacity integer, is_accessible bit, created_at datetime(6) not null, id bigint not null auto_increment, school_id bigint not null, updated_at datetime(6), room_number varchar(20), building varchar(50), name varchar(100) not null, accessibility_features TEXT, primary key (id)) engine=InnoDB;
create table courses (credits integer, classroom_id bigint, created_at datetime(6) not null, id bigint not null auto_increment, instructor_id bigint, updated_at datetime(6), academic_year varchar(20), course_code varchar(20) not null, semester varchar(100), name varchar(200) not null, description TEXT, primary key (id)) engine=InnoDB;
create table enrollments (completion_date date, enrollment_date date not null, grade decimal(5,2), letter_grade varchar(5), course_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, student_id bigint not null, updated_at datetime(6), status varchar(20), primary key (id)) engine=InnoDB;
create table notifications (is_read bit not null, created_at datetime(6) not null, id bigint not null auto_increment, read_at datetime(6), user_id bigint not null, type varchar(50), title varchar(200) not null, message TEXT not null, primary key (id)) engine=InnoDB;
create table scholarship_applications (academic_merit_score integer, amount_approved decimal(10,2), amount_requested decimal(10,2) not null, application_date date not null, disbursement_date date, financial_need_score integer, created_at datetime(6) not null, id bigint not null auto_increment, reviewed_at datetime(6), reviewed_by bigint, student_id bigint not null, updated_at datetime(6), disbursement_reference varchar(100), scholarship_name varchar(200) not null, justification TEXT, purpose TEXT, review_comments TEXT, status enum ('APPROVED','CANCELLED','DISBURSED','PENDING','REJECTED','UNDER_REVIEW') not null, primary key (id)) engine=InnoDB;
create table schools (active bit not null, established_year integer, student_capacity integer, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), phone varchar(20), zip_code varchar(20), code varchar(50), city varchar(100), country varchar(100), district varchar(100), email varchar(100), state varchar(100), name varchar(200) not null, website varchar(200), address varchar(500), description TEXT, primary key (id)) engine=InnoDB;
create table student_disabilities (student_profile_id bigint not null, disability_type enum ('AUTISM','COGNITIVE','HEARING','MENTAL_HEALTH','MULTIPLE','OTHER','PHYSICAL','SPEECH','VISUAL')) engine=InnoDB;
create table student_profiles (current_year integer, date_of_birth date, enrollment_date date, gpa decimal(4,2), graduation_date date, has_disability bit, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, gender varchar(10), emergency_contact_phone varchar(20), student_number varchar(50), emergency_contact_name varchar(100), major varchar(100), accommodations_needed TEXT, assistive_technology TEXT, medical_conditions TEXT, primary key (id)) engine=InnoDB;
create table users (active bit not null, email_verified bit, created_at datetime(6) not null, id bigint not null auto_increment, last_login datetime(6), refresh_token_expiry datetime(6), school_id bigint, updated_at datetime(6), phone varchar(20), username varchar(50) not null, email varchar(100) not null, first_name varchar(100), last_name varchar(100), refresh_token varchar(500), password varchar(255) not null, role enum ('ADMIN','PARENT','SCHOOL_ADMIN','STUDENT','SUPPORT','TEACHER') not null, primary key (id)) engine=InnoDB;
create index idx_accessibility_student on accessibility_reports (student_id);
create index idx_accessibility_school on accessibility_reports (school_id);
create index idx_accessibility_date on accessibility_reports (report_date);
create index idx_classroom_school on classrooms (school_id);
create index idx_classroom_name on classrooms (name);
create index idx_course_classroom on courses (classroom_id);
alter table courses add constraint idx_course_code unique (course_code);
create index idx_enrollment_student on enrollments (student_id);
create index idx_enrollment_course on enrollments (course_id);
create index idx_notification_user on notifications (user_id);
create index idx_notification_read on notifications (is_read);
create index idx_notification_created on notifications (created_at);
create index idx_scholarship_student on scholarship_applications (student_id);
create index idx_scholarship_status on scholarship_applications (status);
create index idx_scholarship_date on scholarship_applications (application_date);
create index idx_school_name on schools (name);
create index idx_school_active on schools (active);
alter table schools add constraint UK_m5x8j64nhdcprk9ghc6622swx unique (code);
create index idx_student_user on student_profiles (user_id);
alter table student_profiles add constraint idx_student_number unique (student_number);
alter table student_profiles add constraint UK_hlcwb2egnj8mj3e0mouse1lgy unique (user_id);
create index idx_user_role on users (role);
alter table users add constraint idx_user_username unique (username);
alter table users add constraint idx_user_email unique (email);
alter table accessibility_reports add constraint FK8w6bt2hyk8eys11gr0mk685r2 foreign key (school_id) references schools (id);
alter table accessibility_reports add constraint FKarqct5asrggdnjng51ypkbysh foreign key (student_id) references student_profiles (id);
alter table classrooms add constraint FKstm3c7u1s7l0t42gywsldaani foreign key (school_id) references schools (id);
alter table courses add constraint FKpeln8go5av13clo5fglfep9xb foreign key (classroom_id) references classrooms (id);
alter table courses add constraint FKcyfum8goa6q5u13uog0563gyp foreign key (instructor_id) references users (id);
alter table enrollments add constraint FKho8mcicp4196ebpltdn9wl6co foreign key (course_id) references courses (id);
alter table enrollments add constraint FKenh264ay3d1nd1lncabcwu59g foreign key (student_id) references student_profiles (id);
alter table notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users (id);
alter table scholarship_applications add constraint FKjn5l691a0p1ppqxhcdup905x4 foreign key (student_id) references student_profiles (id);
alter table student_disabilities add constraint FKdxyx3hicex3awotg8pab1okqd foreign key (student_profile_id) references student_profiles (id);
alter table student_profiles add constraint FK32koy3tgqtaujxhfsn0b9pel2 foreign key (user_id) references users (id);
alter table users add constraint FK3gj5j7vnsoxf1wp9n5hsqdiq3 foreign key (school_id) references schools (id);
