-- Create school table and update users table
CREATE TABLE IF NOT EXISTS school (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    city VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(20),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS email VARCHAR(100) NOT NULL,
    ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS last_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL,
    ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS last_login TIMESTAMP,
    ADD COLUMN IF NOT EXISTS refresh_token VARCHAR(500),
    ADD COLUMN IF NOT EXISTS refresh_token_expiry TIMESTAMP,
    ADD COLUMN IF NOT EXISTS school_id BIGINT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP,
    ADD CONSTRAINT fk_user_school FOREIGN KEY (school_id) REFERENCES school(id),
    ADD CONSTRAINT uk_user_email UNIQUE (email);

CREATE INDEX IF NOT EXISTS idx_user_role ON users(role);